// Number Methods
console.log(Math.round(5.5))
console.log(Math.ceil(4.4))
console.log(Math.max(2,4,10,3,5,8,9))
console.log(Math.floor(3.8))
console.log(Math.trunc(4.9))
console.log(Math.sign(0))
console.log(Math.sign(-4))
console.log(Math.sign(5))
console.log(Math.pow(5,4))